### ISSUE TITLE
Booster queue

### ISSUE THREAD

**Issue by Mythyryn** [CecerMCProjects/HypixelUtils#17] opened 2015-02-03 01:14 UTC
Booster Queue layout is broken again.
http://i.imgur.com/RV0fG9m.png

**Comment by Cecer** [comment] 2015-02-03 09:14
Cannot reproduce. I'll get more details before considering this invalid.

**Comment by Cecer** [comment] 2015-02-05 11:24
Fixed in 1.2.4.

**Closed as completed by Cecer** 2015-02-05 11:24 UTC
Labels: bug, broken by update, chat, fixed/added
